name = "myracecal"
compatibility_date = "2024-01-01"

[env.production]
name = "myracecal"
routes = [
  { pattern = "myracecal.app", custom_domain = true },
  { pattern = "www.myracecal.app", custom_domain = true }
]

